#!/bin/sh
if [ $# != 0 ]; then
	echo 'dotoolc writes its stdin to the pipe being read by dotoold.
dotoolc will exit immediately if the pipe is not being read.
The path of the pipe is $DOTOOL_PIPE else /tmp/dotool_pipe.
' >&2
	[ "$1" = -h ] || [ "$1" = --help ]; exit
fi

fifo_being_read(){
	[ -p "$1" ] && /bin/echo 1<>"$1" >"$1"
}

p="${DOTOOL_PIPE:-/tmp/dotool_pipe}"

if [ -p "$p" ] && ! [ -w "$p" ]; then
	echo 'dotoolc: the pipe does not grant write permission'
	exit 1
fi
if ! fifo_being_read "$p"; then
	echo 'dotoolc: dotoold is not connected' >&2
	exit 1
fi
exec cat > "$p"
